# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "29b49298063da4f8633daaeb2e652e39"
name = "ReviewMaster"
application_url = "https://reviewmaster-app.azurewebsites.net"
embedded = true
handle = "reviewmaster-reviews"

[webhooks]
api_version = "2026-07"

  [[webhooks.subscriptions]]
  uri = "/api/webhooks/compliance"
  compliance_topics = [ "customers/data_request", "customers/redact", "shop/redact" ]

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_orders,read_products,write_products,read_script_tags,write_script_tags,read_themes,write_themes"
use_legacy_install_flow = true
optional_scopes = [ ]

[auth]
redirect_urls = [
  "https://reviewmaster-app.azurewebsites.net/api/auth/callback"
]
